apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: mocktail
spec:
  collectors:
    - logs:
        selector:
          - app=mocktail
        limits:
          maxAge: 30d
          maxLines: 10000
    - run:
        namespace: mocktail-replicated
        collectorName: ping-google
        image: flungo/netutils
        command: ["ping"]
        args: ["www.google.com"]
        timeout: 5s
    - http:
        collectorName: echo-ip
        get:
          url: https://api.replicated.com/market/v1/echo/ip